### ISSUE TITLE
Make <Enter> return to beginning of "line".

### ISSUE THREAD

**Issue by labseven** [olin/SoftSysCollascii#20]
Save the last position since pressing arrow keys, and return to it (one line down or right)

**Comment by newsch** [comment]
@MatthewBeaudouinLafon and I had some trouble capturing the enter key on Friday. On his machine it returned `\r`, but `ncurses` seemed to be expecting `\n` for `KEY_ENTER`. Luckily it looks like you can redefine keys (but not clear yet if both `\r` and `\n` could map to `KEY_ENTER` at the same time.

- [`define_key` man page](https://invisible-island.net/ncurses/man/define_key.3x.html)
- [`get_ch` man page (with key listings)](https://invisible-island.net/ncurses/man/curs_getch.3x.html)
